### ISSUE TITLE
Contribute riboviz to nf-core?

### ISSUE THREAD

**Issue by ewallace** [riboviz/workflows#3] opened 2020-04-10 11:10 UTC
As a long-term goal, if/when riboviz is implemented in nextflow, would we want to contribute it to the [nf-core](https://nf-co.re/) collection? Would increase discoverability/review/usability.

**Comment by mikej888** [comment] 2020-05-20 15:25
See issue Explore how to contribute RiboViz Nextflow to nf-core riboviz/riboviz#175.

**Comment by mikej888** [comment] 2020-05-20 15:25
Closed as now duplicated in riboviz/riboviz.

**Comment by kavousan** [comment] 2020-08-05 15:37
We reject as it is a duplicate of riboviz/riboviz#175.

**Closed as completed by kavousan** 2020-08-05 15:37 UTC
